---
title: "Lab11"
output: pdf_document
date: "2024-11-24"
---

# 1. 

Summarize your findings from examining the pairwise scatterplots and correlation matrix.

\newpage

# 2. 

Discuss whether the VIFs indicate any explanatory variables exhibiting extreme multicollinearity.

\newpage 

# 3. 

Summarize the backward elimination method of model selection by providing:

## (a) 

An ordered list of which variable was removed from the model at each step;


## (b) 

A list of which variables remained in the final model;

## (c) 

A summary of the partial regression coefficients effects tests for the final model.

\newpage 

# 4. 

Summarize the forward selection method of model selection by providing:

## (a) 

An ordered list of which variable was added to the model at each step;

## (b) 

A list of which variables never entered the final model;

## (c) 

A summary of the partial regression coefficients effects tests for the final model.

\newpage 

# 5. 

Summarize the all-possible-subsets method of model selection by providing:

## (a) 

Which model would you choose based on the adjusted $R^2$ values?

## (b) 

Which model would you choose based on the Mallow's $C_p$ criteria?

## (c) 

Which model would you choose based on the $BIC$ values?

\newpage 

# 6. 

Interpret the values of the estimated regression coefficients in the context of the study for:

## (a) 

The two values corresponding to the categorical age variable;

## (b) 

One of the values corresponding to the quantitative variable of your choice.

\newpage 

# 7. 

Summarize your findings from examining all the residual plots used to diagnose the MLR model assumptions. Are there any assumptions that aren’t met for this analysis?

\newpage 

# 8. 

Summarize your findings from examining the case diagnostic values/plots. Are there any outliers, leverage points, or influential observations?

