---
title: "PS1 Notes"
output: html_document
date: "2024-08-24"
---

0. What is an experiment? 

Experiment: an investigation in which the investigator applies (assigns) some treatments to experimental units and then observes the effect of the treatments on the experimental units by measuring one or more response variables.

1.  What are experimental units.

Experimental Unit: the physical entity to which a treatment is randomly assigned and independently applied. The smallest division of material (e.g. land,
plant, animal, etc) to be studied 

2.  What are observational units.

Observational Unit: the unit on which a response variable is measured. There is often a one-to-one correspondence between experimental units and observational units, but that is not always true.

3.  What are treatments.

Treatment: a condition or set of conditions applied to experimental units in an experiment.

4.  What is a response variable.

Response Variable: a characteristic of an experimental unit that is measured after treatment and analyzed to assess the efects of treatments on experimental units. (e.g. yield, gene expression level, etc.)


5.  What is replication? 

  - Applying a treatment independently to two or more experimental units
  - Level of variability can be estimated for units that are treated alike

6.  What is blocking? 

Blocking/Matching 
  - Group similar experimental units into blocks Apply each treatment to (the same number of) experimental units within each block (balance)
  - Separate random assignment of units to treatments is done within each block (randomization)

7.  What is randomization? 

  - Random assignment of treatments to experimental units
  - Reduce or eliminate sources of bias (treatment groups are equivalent, on average, except for the assigned treatment)
  - Cause and effect relationships can be demonstrated
  - Create a probability distribution for a test statistic under the
null hypothesis of no treatment effects
