---
output: pdf_document
keep_tex: yes 
---

[Stat 5000]{.smallcaps}
[Homework #1]{.smallcaps}\
[Fall 2024]{.smallcaps}
[due Fri, Sep 6th @ 11:59 pm]{.smallcaps}\
[Name: Samuel Olson]{.smallcaps} \

**Directions:** Type or clearly handwrite your solutions to each of the following exercises. Partial credit cannot be given unless all work is shown. You may work in groups provided that each person takes responsibility for understanding and writing out the solutions. Additionally, you must give proper credit to your collaborators by providing their names on the line below (if you worked alone, write "No Collaborators\"):\

[Collaborators: ]{.smallcaps}\

**1. [+10]:** Some researchers were interested in studying the effects of different fertilizer amount (Low Nitrogen and High Nitrogen) and different genotypes (one energy line and one grain line) of sorghum on biomass. For each genotype, six pots of one-week-old seedlings were available, and each pot held one seedling. For each genotype, the researchers randomly assigned three pots to high nitrogen treatment (H) and the remaining three pots to low nitrogen (L) treatment. After 2 weeks, the fresh weight for each seedling was measured. In total, there are 12 observations.\

  1.  Identify the experimental units.\
    A pot containing one one-week-old seedling
  
  2.  Identify the observational units.\
    [A pot containing] one one-week-old seedling
  
  3.  Identify the treatments.\
    The treatments were either a high nitrogen treatment (H) or a low nitrogen treatment (L)
  
  4.  Identify the response variable.\
    The biomass of the seedling after 2 weeks of being treated (weight of the sorghum)
  
  5.  Does the experiment utilize replication? Answer yes/no and provide a brief justification.\
    Yes, but this is more due to the lack of information about possible differences in how the seedlings were treated during the 2 week period (same amount of sunlight, water, environs, etc. are not explicitly noted). 
  
  6.  Does the experiment utilize blocking? Answer yes/no and provide a brief justification.\
  Yes, as first the researchers divided up the seedlings by genotype and then randomly assigned the treatments.
  
  7.  Does the experiment utilize randomization? Answer yes/no and provide a brief justification.\
  Yes. After grouping by genotype, the selection of which pot/seedling was given which treatment was randomly decided; however, it is worth noting that the number of seedlings given a particular in each group was fixed, so there was an intervention to make this not "truly random". 

**2. [+10]:** A statistics teacher wanted to determine if having business students use clickers to respond to questions posed in a business statistics class would improve student learning. The teacher decided to have students use clickers in one class of introductory business statistics 226. She did not have students use clickers in a second class of business statistics 226 that she taught during the same semester. She tossed a coin to select the class to use the clickers. She used the same book and the same lectures in both classes and gave the same assignments and same exams to both classes. There were 90 students in each class. At the end of the semester, she compared the final exam scores for the students in the class that used clickers to the final exam scores for the students in the class that did not use clickers.\

  1.  Identify the experimental units.\
    The class of business students taking Statistics 226(0)
  
  2.  Identify the observational units.\
    A student of the class (individual)
  
  3.  Identify the treatments.\
    Whether a clicker was provided for use in class (or not)
  
  4.  Identify the response variable.\
    The final exam scores of students in a class (one final exam score per student)
  
  5.  Does the experiment utilize replication? Answer yes/no and provide a brief justification.\
    Yes. Assuming classes are mutually exclusive and there was never any overlap in students attending, then both classes were treated exactly alike aside from the difference in treatment, i.e. given the same lectures, same assignments, and same exams 
  
  6.  Does the experiment utilize blocking? Answer yes/no and provide a brief justification.\
  Yes, all students in a class were given the same treatment (a clicker or lack of clicker)
  
  7.  Does the experiment utilize randomization? Answer yes/no and provide a brief justification.\
  Yes, the choice of which class would receive the clickers was randomly determined through a coin toss, though again I'd argue this isn't "truly random" in the sense that a student's treatment was conditional on their class (though understandably so, as having variance within a class about choice of clicker would likely compromise the study)

**3. [+30]:** The file `guinea_pigs.csv` (available on Canvas) contains data on survival times (in days) of guinea pigs that were randomly assigned either to a control group or to a treatment group that received a dose of tubercle bacilli (Doksum, K. (1974), *Annals of Statistics*, pp 267-77).

```{r setup, echo = T, warning = F}
# knitr::opts_chunk$set(echo = F)
library(dplyr)
guinea_pigs <- read.csv("C:/Users/samue/Downloads/guinea_pigs.csv")
# summary(guinea_pigs)
controlData <- guinea_pigs %>% 
      filter(Treatment == "Control") %>% 
      na.omit()
treatmentData <- guinea_pigs %>% 
      filter(Treatment == "Bacilli") %>% 
      na.omit()

summary(controlData)
summary(treatmentData)
```

  1.  Use R to compute the following summary statistics for each treatment group:

    Statistic            Control                     Bacilli 
    -------------------- --------------------------- ---------------------------
    Median                                           
                                                     
    Q1                                               
                                                     
    Q3                                               
                                                     
    IQR                                              
                                                     
    Sample Mean                                      
                                                     
    Standard Deviation   

  2.  Use R to construct side-by-side box plots of survival times for the two treatment groups and include it with this assignment.\
  
  3.  Use the box plots from part (b) and the summary statistics from part (a) to describe and compare features of the distributions of survival times for the two treatment groups.\
  
  4.  There is no function built into R to easily perform the randomization test to determine whether the average survival times of the guinea pigs in the two treatment groups is the same or different. Write your own function to perform the test (there is an example in the optional R lab). Interpret the results by providing\

    1.  the null and alternative hypotheses;\
      Text 
    
    2.  observed test statistic;\
      Text
    
    3.  randomization histogram;\
      Text
    
    4.  p-value;\
      Text
    
    5.  interpretation of the test results (stated in the context ofthe problem).\
      Text

**Total:** 50 points **\# correct:** **%:**


