---
title: "Lab 1"
output: pdf_document
---

[Stat 5000]{.smallcaps}[Lab #1]{.smallcaps}\
[Fall 2024]{.smallcaps} [Due Tue Sept 3rd]{.smallcaps}
[Name: Sam Olson]{.smallcaps} \

**Directions:** Complete the exercises below. When you are finished,
turn in any required files online in Canvas, then check-in with the Lab
TA for dismissal.\

**[Assignment]{.underline}**

## Q: 1.  Calculate the sample mean score for each treatment group. What is the difference in the two sample means?

### A: 

Text 

\pagebreak

## Q: 2.  Use SAS to create a comparative box-plot for the sample mean score for each treatment group. Describe what you see.

### A: 

Text 

\pagebreak

## Q: 3.  What are the null and alternative hypotheses for the randomization test necessary to explore the research question?

### A: 

Text

\pagebreak

## Q: 4.  Conduct a randomization test for these data in SAS (be sure to keep the random seed set at 500 so everyone gets the same answer) and study the reference distribution for the difference in the sample means for the 10,000 random assignments of treatments to subjects. Describe the shape, center and variability of this distribution.

### A: 

Text

\pagebreak

## Q: 5.  Locate the observed difference in the sample means from part (a) on
    the reference distribution. Given the observed difference in the
    sample means from part (a), what is the p-value for this
    randomization test?

### A: 

Text

\pagebreak

6.  Interpret the results of the test in the context of the research question.

### A: 

Text

\pagebreak

## Q: 7.  What aspects of the data collection in this experiment would need special attention by the researcher?
    
### A: 

Text

**Total:** 20 points **\# correct:** **%:**
