---
title: "PS2"
author: "Sam Olson" 
output: pdf_document
date: "2025-01-29"
---

# Problem 1

Suppose $\mathbf{y} \sim \mathcal{N}(\boldsymbol{\mu}, \mathbf{\Sigma})$, where $\boldsymbol{\mu}^T = [1 \quad 2 \quad 3]$

$$
\boldsymbol{\mu}^T = [1 \quad 2 \quad 3] \quad \text{and} \quad \mathbf{\Sigma} = 
\begin{bmatrix}
2 & 1 & -1 \\
1 & 2 & 1 \\
-1 & 1 & 3
\end{bmatrix}
$$

Further, define a $3 \times 3$ matrix $A$ and a $2 \times 3$ matrix $B$ as follows

$$
\mathbf{A} = 
\begin{bmatrix}
2 & 2 & 1 \\
1 & 0 & -1 \\
0 & 1 & -1
\end{bmatrix} \quad \text{and} \quad \mathbf{B} = 
\begin{bmatrix}
1 & 1 & 1 \\
-1 & 1 & 0
\end{bmatrix}
$$

a) Determine the distribution of $u = \mathbf{1}_3^T \mathbf{y}$.

b) Determine the distribution of $\mathbf{v} = \mathbf{Ay}$.

c) Determine the distribution of $\mathbf{w}$, where $\mathbf{w}^T = [\mathbf{Ay} \quad \mathbf{By}]$.

d) Which of the distributions obtained in (a)-(c) are singular distributions? Recall that a distribution is singular if $\mathbf{\Sigma}$ is positive definite. Note that there are many algebraic properties of $\mathbf{\Sigma}$ that can be used to show that $\mathbf{\Sigma}$ is singular/nonsingular.

\newpage 

# Problem 2

Suppose $\mathbf{X}$ and $\mathbf{W}$ are any two matrices with $n$ rows for which $\mathcal{C}(\mathbf{X}) = \mathcal{C}(\mathbf{W})$. Show that $\mathbf{P_X} = \mathbf{P_W}$.

\newpage 

# Problem 3

Consider a competition among 5 table tennis players labeled 1 through 5. For $1 \leq i < j \leq 5$, define $y_{ij}$ to be the score for player $i$ minus the score for player $j$ when player $i$ plays a game against player $j$. Suppose for $1 \leq i < j \leq 5$,

$$
y_{ij} = \beta_i - \beta_j + \epsilon_{ij},
$$

where $\beta_1, \ldots, \beta_5$ are unknown parameters and the $\epsilon_{ij}$ terms are random errors with mean 0. Suppose four games will be played that will allow us to observe $y_{12}, y_{34}, y_{25},$ and $y_{15}$. Let

$$
\mathbf{y} =
\begin{bmatrix}
y_{12} \\
y_{34} \\
y_{25} \\
y_{15}
\end{bmatrix},
\quad \boldsymbol{\beta} =
\begin{bmatrix}
\beta_1 \\
\beta_2 \\
\beta_3 \\
\beta_4 \\
\beta_5
\end{bmatrix},
\quad \text{and} \quad \boldsymbol{\epsilon} =
\begin{bmatrix}
\epsilon_{12} \\
\epsilon_{34} \\
\epsilon_{25} \\
\epsilon_{15}
\end{bmatrix}.
$$

a) Define a model matrix $\mathbf{X}$ so that model (1) may be written as $\mathbf{y} = \mathbf{X} \boldsymbol{\beta} + \boldsymbol{\epsilon}$.

b) Is $\beta_1 - \beta_2$ estimable? Prove that your answer is correct.

c) Is $\beta_1 - \beta_3$ estimable? Prove that your answer is correct.

d) Find a generalized inverse of $\mathbf{X}^\top \mathbf{X}$.

e) Find a solution to the normal equations in this particular problem involving table tennis players.

f) Find the Ordinary Least Squares (OLS) estimator of $\beta_1 - \beta_5$.

g) Give a linear unbiased estimator of $\beta_1 - \beta_5$ that is not the OLS estimator.

\newpage 

# Problem 4

Consider a linear model for which

$$
\mathbf{y} =
\begin{bmatrix}
y_1 \\
y_2 \\
y_3 \\
y_4 \\
y_5 \\
y_6 \\
y_7 \\
y_8
\end{bmatrix},
\quad \boldsymbol{\beta} =
\begin{bmatrix}
\beta_1 \\
\beta_2 \\
\beta_3 \\
\beta_4
\end{bmatrix},
\quad \text{and} \quad \mathbf{X} =
\begin{bmatrix}
1 & 1 & 1 & -1 \\
1 & 1 & 1 & -1 \\
1 & 1 & -1 & 1 \\
1 & 1 & -1 & 1 \\
1 & -1 & 1 & 1 \\
1 & -1 & 1 & 1 \\
-1 & 1 & 1 & 1 \\
-1 & 1 & 1 & 1
\end{bmatrix}.
$$

a) Obtain the normal equations for this model and solve them.

b) Are all functions $\mathbf{c}^\top \boldsymbol{\beta}$ estimable? Justify your answer.

c) Obtain the least squares estimator of $\beta_1 + \beta_2 + \beta_3 + \beta_4$.

\newpage 

# Problem 5

Suppose the Gauss-Markov model with normal errors (GMMNE) holds.

a) Suppose $\mathbf{C} \boldsymbol{\beta}$ is estimable. Derive the distribution of $\mathbf{C}\boldsymbol{\hat{\beta}}$, the OLSE of $\mathbf{C\beta}$.

b) Now suppose $\mathbf{C} \boldsymbol{\beta}$ is NOT estimable. Provide a fully simplified expression for $\text{Var}\left(\mathbf{C(X^\top X)^\top X^\top y} \right)$.

c) Now suppose $H_0: \mathbf{C} \boldsymbol{\beta} = \mathbf{d}$ is testable and that $\mathbf{C}$ has only one row and $\mathbf{d}$ has only one element so that they may be written as $\mathbf{c}^\top$ and $\mathbf{d}$, respectively. Prove the result on slide 29 of slide set 2 of Key Linear Model Results.

\newpage 

# Problem 6

Provide an example that shows that a generalized inverse of a symmetric matrix need not be symmetric. 

(Comment: For this reason, we cannot assume that $(\mathbf{X}^\top \mathbf{X})^- = [(\mathbf{X}^\top \mathbf{X})^-]^\top$.)