---
title: "PS2"
output:
  pdf_document: default
  html_document: default
---

[Stat 5000]{.smallcaps}[Homework #2]{.smallcaps}\
[Fall 2024]{.smallcaps} [due Fri, Sep 13th @ 11:59 pm]{.smallcaps}
[Name: Sam Olson]{.smallcaps} \

**Directions:** Type or clearly handwrite your solutions to each of the following exercises. Partial credit cannot be given unless all work is shown. You may work in groups provided that each person takes responsibility for understanding and writing out the solutions. Additionally, you must give proper credit to your collaborators by providing their names on the line below (if you worked alone, write "No Collaborators"):\

[Collaborators: XXX]{.smallcaps} \

> 1. **[+10]:** For a study about a new treatment for pancreatic cancer, 100 pancreatic cancer patients are recruited. For ethical reasons every patient in the study is given the highest current standard of care which consists of surgery to remove cancerous tumors from the pancreas followed by a period of radiation therapy. After receiving the standard treatment, each patient is given the opportunity to have a second experimental treatment that consists of coating some of the cancerous cells removed from the patient during surgery with an antigen that the human body will reject and injecting the coated cells back into the pancreas of the same patient. The basic idea is that this second treatment will help prevent recurrence of cancer tumors because the patient's immune system will attack the coated cells and also attack other cancerous cells in the pancreas that the surgery and radiation treatments may have missed. The 57 patients who volunteer for the second treatment and the 43 patients who refuse the second treatment are followed for three years to determine how long each patient survives.

>> 1.  Is this study an experiment or observational study? Justify your
    answer.

>> 2.  Identify the experimental or sampling units.

>> 3.  Identify the response variable.

>> 4.  Identify the treatments or study/population conditions.

>> 5.  Describe whether or not control of extraneous variation was used
    in this study.

>> 6.  Describe whether or not randomization was used in this study.

>> 7.  Describe whether or not replication was used in this study.

\newpage 

> 2. **[+10]:** The following study explores systolic blood pressure measurements for thirty subjects after receiving an assigned treatment for six weeks, either a new drug or the gold standard. The data are posted as `systolic.txt`. Each line contains the information for a subject: patient identification number, treatment group (coded 1 for new drug and 2 for gold standard), systolic blood pressure. The research interest is to answer the question: "Does the new drug produce lower mean systolic blood pressure level in hypertensive patients than the gold standard?\"

>> 1.  Using SAS, conduct an appropriate two-sample $t$-test, assuming homogeneous variances. Provide a screenshot of the relevant SAS output here.

>> 2.  What is the value of a two-sample $t$-statistic and its corresponding degrees of freedom?

>> 3.  What is the $p$-value?

>> 4.  Interpret the results of the $t$-test in the context of this study.

\newpage 

> 3. **[+5]:** Perform a randomization test in SAS of the research question given in problem 2 by computing the difference in the sample means for each of 25,000 data sets created from new random assignments of 30 patients to one of the two drugs.

>> 1.  Obtain an approximate $p$-value for the randomization test.

>> 2.  Interpret the result of the randomization test in the context of this study. Is it consistent with your response to problem 2(d)?

>> 3.  Which sampling distribution is the randomization histogram approximating?

**Total:** 25 points **\# correct:** **%:**
