---
title: "HW9"
output: pdf_document
date: "Sam Olson"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Q1

Let $X_1, \ldots, X_n$ be iid exponential($\theta$) and let $\hat{\theta}_n \equiv \bar{X}_n \equiv \sum_{i=1}^n X_i/n$ denote the MLE based on $X_1, \ldots, X_n$.

## a)

Determine the limiting distribution of $\sqrt{n}(\hat{\theta}_n - \theta)$ as $n \to \infty$.

## b)

Find a variance stabilizing transformation (VST) for $\{\hat{\theta}_n\}$ and use this to determine a large sample confidence interval for $\theta$ with approximate confidence coefficient $1 - \alpha$.

## c)

Suppose a random sample $X_1, \ldots, X_{100}$ of $n = 100$ observations yields $\bar{x}_n = 1.835464$. Use this information to obtain a large sample confidence interval for $\theta$ based on a likelihood ratio statistic, which has approximate confidence coefficient $90\%$. (Use the chi-squared approximation for this; you should be able to then numerically determine the interval.) Using this data, compute also a confidence interval with approximate confidence coefficient $90\%$ using the VST approach from part(b).

\newpage

# Q2

For $\theta > 0$, suppose that $X_1, \ldots, X_n$ are iid Uniform(0, $\theta$). Consider the MLE of $\theta$, which is given by $\hat{\theta}_n = \max\{X_1, X_2, \ldots, X_n\}$.

# a)

Prove that, in distribution, $n(\theta - \hat{\theta}_n) \overset{d}{\longrightarrow}$ Exponential($\theta$) as $n \to \infty$ (i.e., converges in distribution to an exponential with mean $\theta$).

(Hint: Evaluate $P_{\theta}[n(\theta - \hat{\theta}_n) > t]$ and remember that $\lim_{s \to \infty}(1 + \frac{a}{s})^s = \exp(a)$.)

## b)

Argue carefully that $\{\theta > 0 : \theta \leq n\hat{\theta}_n/(n - \log(20))\}$ can be used as a one-sided (upper) confidence interval for $\theta$ with approximate confidence coefficient $95\%$ (that is, show that the interval will have an approximate coverage probability of $95\%$ for each $\theta > 0$).

\newpage

# Q3

Suppose $X_1, \ldots, X_n$ are a random sample with common cdf given by

$$
P(X_1 \leq x|\theta) = 
\begin{cases}
1 - e^{-(x/\theta)^2} & \text{if } x > 0 \\
0 & \text{otherwise},
\end{cases}
\quad \theta > 0.
$$

## a)

Use the Mood-Graybill-Boes Method to derive a CI for $\theta$ with C.C. $1 - \alpha$ based on the statistic $X_{(1)} = \min_{1 \leq i \leq n} X_i$.

## b)

Use the Mood-Graybill-Boes Method to derive a CI for $\theta$ with C.C. $1 - \alpha$ based on the statistic $T = \sum_{i=1}^n X_i^2$. Express your confidence interval using chi-squared quantiles.

Note: One can show $X_i^2$ is Exponential($\theta^2$) distributed so that $2T/\theta^2$ is $\chi_{2n}^2$ distributed with $2n$ degrees of freedom.