---
title: "HW2"
author: "Sam Olson"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Q1

Suppose that $\underline{y}$ is an $n \times 1$ observable random vector that follows Model II.

## (a)

If $\underline{\lambda}_1'\underline{\beta}$ and $\underline{\lambda}_2'\underline{\beta}$ are both estimable, is $\underline{\lambda}_1'\underline{\beta} + \underline{\lambda}_2'\underline{\beta}$ necessarily estimable? Explain your answer.

**Answer.**

## (b)

If $\underline{\lambda}_1'\underline{\beta}$ and $\underline{\lambda}_2'\underline{\beta}$ are both nonestimable, is $\underline{\lambda}_1'\underline{\beta} + \underline{\lambda}_2'\underline{\beta}$ necessarily nonestimable? Explain your answer.

**Answer.**

## (c)

Can $\underline{\lambda}_1'\underline{\beta} + \underline{\lambda}_2'\underline{\beta}$ be estimable if $\underline{\lambda}_1'\underline{\beta}$ is estimable and $\underline{\lambda}_2'\underline{\beta}$ is nonestimable? Explain your answer.

**Answer.**

# Q2

Take the model to be Model VII and suppose that

$$\underline{y} = \begin{pmatrix} 2 \\ 3 \\ 4 \end{pmatrix} \quad \text{and} \quad X = \begin{pmatrix} 1 & 2 & 3 \\ 2 & 3 & 1 \\ 0 & 0 & 0 \end{pmatrix}.$$

## (a)

Find the orthogonal projections of $\underline{y}$ on $\mathcal{C}(X)$ and on $\mathcal{C}^{\perp}(X)$.

**Answer.**

## (b)

Determine $\mathrm{rank}(X'X)$.

**Answer.**

## (c)

Use the following method and find a generalized inverse of $X'X$.

Let $A$ be an $n \times m$ matrix of rank $r \geq 1$. Let $B$ be a nonsingular $r \times r$ submatrix of $A$. For matrix $A$, replace the entries of $B$ by those of $(B^{-1})'$, and replace all other entries of $A$ by $0$. Then the transpose of the resulting matrix is a generalized inverse of $A$.

**Answer.**

## (d)

Compute a solution $\hat{\underline{\beta}}$ to the normal equations.

**Answer.**

## (e)

Check that the vectors $X\hat{\underline{\beta}}$ and $\underline{y} - X\hat{\underline{\beta}}$ agree with your results in part (a).

**Answer.**

# Q3

For Model VII, partition $\underline{y}$, $X$, and $\underline{\epsilon}$ correspondingly as follows:

$$\underline{y} = \begin{pmatrix} \underline{y}_1 \\ \underline{y}_2 \end{pmatrix}, \quad X = \begin{pmatrix} X_1 \\ X_2 \end{pmatrix}, \quad \text{and} \quad \underline{\epsilon} = \begin{pmatrix} \underline{\epsilon}_1 \\ \underline{\epsilon}_2 \end{pmatrix}.$$

Suppose that the row spaces of $X_1$ and $X_2$ are essentially disjoint, that is, $\mathcal{R}(X_1) \cap \mathcal{R}(X_2) = \{\underline{0}'\}$. Show that, if $\underline{\lambda}' \in \mathcal{R}(X_1)$, then the least squares estimate of $\underline{\lambda}'\underline{\beta}$ based on the model $\underline{y}_1 = X_1\underline{\beta} + \underline{\epsilon}_1$ is the same as the least squares estimate of $\underline{\lambda}'\underline{\beta}$ based on the model $\underline{y} = X\underline{\beta} + \underline{\epsilon}$.

*Hint: Under the full model, the LSE is $\underline{a}'X'\underline{y} = \underline{a}'X_1'\underline{y}_1 + \underline{a}'X_2'\underline{y}_2$ and, under the partial model, the LSE is $\underline{b}'X_1'\underline{y}_1$ where here $X_1'X_1\underline{a} + X_2'X_2\underline{a} = X'X\underline{a} = \underline{\lambda} = X_1'X_1\underline{b}$ (why?); in the last equation, move terms involving $X_2'$ and $X_1'$ to different sides.*

**Answer.**

# Q4

Show that, under Model II, $\underline{a}'\underline{y}$ is a BLUE of its expectation if and only if $\underline{a} \in \mathcal{C}(X)$.

**Answer.**

# Q5

## (a)

Show that, under Model II, the problem of determining the BLUE $\underline{a}'\underline{y}$ of an estimable function $\underline{\lambda}'\underline{\beta}$ is equivalent to that of minimizing $\underline{a}'\underline{a}$ subject to the constraints $\underline{a}'X = \underline{\lambda}'$.

**Answer.**

## (b)

The Lagrangian function associated with this minimization problem is

$$L(\underline{a}, \underline{\rho}) = \underline{a}'\underline{a} + 2\underline{\rho}'(X'\underline{a} - \underline{\lambda}).$$

Use the vector calculus to differentiate the Lagrangian function with respect to $\underline{a}$ and the Lagrangian multipliers, and set these derivatives equal to zero.

**Answer.**

## (c)

Show that the resulting equations have a solution if and only if the conjugate normal equations are consistent.

**Answer.**

## (d)

Solve your equations for the minimizing value of $\underline{a}$.

**Answer.**
