---
title: "HW5"
output:
  pdf_document: default
  html_document: default
date: "2024-09-29"
---
  
# Homework 5 
NOT DUE 

# Q1: (a), (b)

For a family of cdfs $F(x | \theta), \theta \in \Theta$, we can say that the cdfsare stochastically ordered if $\theta_1 > \theta_2$ imples that $$F(x | \theta_1) \leq F(x | \theta_2)$$ for any $x \in \mathbb{R}$, i.e. $$1 - F(x|\theta_1) \geq 1 - F(x | \theta_2)$$

## Q1: (a)

Show that a location family is stochastically ordered in terms of the location parameter. 

## A1: (a) 

## Q1: (b)

If the sample space (or range of the random variable) is $[0, \infty)$, show that a scae family is stochastically ordered in terms of the scale parameter. 

## A1: (b)

\newpage
# Q2: 4.1, Casella & Berger, (a), (b), (c)

A random point (X, Y) is distributed uniformly on the square with vertices (1,1), (1, -1), (-1,1), and (-1, -1). That is, the joint pdf is $f(x, y) = \frac{1}{4}$ on the square. Determine the probabilities of the following events. 

Note: The joint pdf is $$f(x, y) = \frac{1}{4}$$ constant for -1<x<1, -1<y<1 here; probability (integrals under joint pdf) will be determined as "an (x,y) subregion of (-1, 1) X (-1, 1)" multiplied by $\frac{1}{4}$. 

## Q2: (a) 

$$X^2 + Y^2 < 1$$

## A2: (a) 

## Q2: (b) 

$$2X - Y > 0$$

## A2: (b) 

## Q2: (c) 

$$|X + Y| < 2$$

## A2: (c) 

\newpage
# Q3: 4.4, Casella & Berger, (a), (b), (c), (d)

A pdf is defined by: 

$$f(x, y) = 
\begin{cases}
  C(x + 2y) 
  & \text{if } 0 < y < 1 
  \text{ and } 0 < x < 2\\
  0 & \text{otherwise}
\end{cases}$$

## Q3: (a) 

Find the value of C. 

## A3: (a) 

## Q3: (b) 

Find the marginal distribution of X. 

## A3: (b) 

## Q3: (c) 

Find the joint pdf of X and Y. 

## A3: (c)

## Q3: (d) 

Find the pdf of the random variable 

$$Z = \frac{9}{(X+1)^2}$$

## A3: (d) 

\newpage
# Q4: 4.5, Casella & Berger, (a), (b)

## Q4: (a) 

Find $P(X > \sqrt{Y})$ if X and Y are jointly distributed with pdf: 

$$f(x, y) = x + y, 0 \leq x \leq 1, 0 \leq y \leq 1$$

## A4: (a) 

## Q4: (b) 

Find $P(X^2 < Y < X)$ if X and Y are jointly distributed with pdf: 

$$f(x, y) = 2x, 0 \leq x \leq 1, 0 \leq y \leq 1$$

## A4: (b) 

\newpage
# Q5: (a), (b), (c), (d)

Suppose that an urn contains 4 balls: 1, 3, 5, 8. We choose two balls at random from the urn without replacement. Let X be the number on the first ball chosen and let Y represent the larger of the numbers appearing on the two balls. 

## Q5: (a)

State the joint pmf for the random vector (X, Y). 

Hint: It might be easier to start with the joint distribution of (X, Z) where X is the number on the first ball chosen and Z is the number on the second ball chosen. There are 12 outcomes possible for (X, Z), each with probability 1/12; these outcomes and probabilities determine the distribution of (X, Y).

## A5: (a) 

## Q5: (b) 

Give the marginal distribution of X and the marginal distribution of Y. 

## A5: (b) 

## Q5: (c) 

Find the expected value of X and the expected value of Y - X. 

## A5: (c) 

## Q5: (d) 

Give the covariancne of X and Y. 

## A5: (d) 

\newpage
# Q6

## Q6 

Consider (X, Y) have the distriution in problem 2 above. Find the mean $\mu_X$ and variance $\sigma^2_X$ of X and the mean $\mu_Y$ and variance $\sigma^2_Y$ of Y, and determine $$E[(X - \mu_X)^2(Y-\mu_Y)^2]$$

## A6

\newpage
# Q7: (a), (b), (c)

Prove or disprove the following. 

## Q7: (a) 

If EX > EY then P(X > Y) = 0. 

Hint: Consider that P(X > Y) = 0 means that $Y \geq X$ with probability 1. 

## A7: (a)

## Q7: (b) 

Suppose that $F_X(x)$ and $F_Y(y)$ are univariate cdfs. Is $F(x, y) \equiv max \{ F_X(x), F_Y(y) \}$ a legitimate bivariate cdf? 

## A7: (b)

## Q7: (c) 

Suppose that $F_X(x)$ and $F_Y(y)$ are univariate cdfs. Is $F(x, y) \equiv min \{ F_X(x), F_Y(y) \} = [F_X(x) + F_Y(y) - |F_X(x) - F_Y(y)|] / 2$ a legitimate bivariate cdf? 

## A7: (c)
